use_frameworks!

platform :ios, '8.0'

target 'MixedStyle_Example' do
  pod 'MixedStyle', :path => '../'

  target 'MixedStyle_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
